;; -*- no-byte-compile: t; -*-
;;; ~/.doom.d/packages.el

(package! dash-at-point)
(package! winum)
(package! exec-path-from-shell :disable t)
(package! pyvenv)
(package! auto-yasnippet)
(package! evil-avy)
(package! evil-ex-fasd)
(package! drag-stuff)
(package! major-mode-hydra)
(package! pcmpl-args)
(package! helm-mode-manager)
(package! helm-make)
(package! helm-ls-git)
(package! helm-swoop)
(package! nswbuff)
(package! ace-popup-menu)
(package! symbol-overlay)
(package! dired-filter)
(package! dired-narrow)
(package! dired-subtree)
(package! dired-sidebar)
(package! dired-launch)
